# Build frontend
FROM node:latest AS frontend
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Copy frontend into nginx html directory
FROM nginx:stable
COPY --from=frontend /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
